### ISSUE TITLE
Suggestion: TODO issues

### ISSUE THREAD

**Issue by bitwalker** [rrrene/elixirstatus-web#1]
Hey there! I'd probably lend a hand when I have time, but it would be helpful if you added issues in the tracker for features/things you feel are in progress/need to be done, and tag them as help-wanted or not, that way people can come in, post a comment saying they are tackling it and/or ask for more direction. Might want to have an RFC tag and post issues under it that represent the things you think are optional and/or need some discussion. You have the TODO list in the README, but it doesn't really identify what's currently in-development, etc.

Just a friendly suggestion from a potential contributor ;)

**Comment by rrrene** [comment]
:+1: I added some issues and also (finally) posted this project to the mailing-list, to lure potential contributors here :wink:

**Comment by bitwalker** [comment]
Oops, sorry I should've closed this since you opened up issues for the TODOs. Thanks again!
