### ISSUE TITLE
Feature: Autosave post during typing

### ISSUE THREAD

**Issue by rrrene** [rrrene/elixirstatus-web#10]
We should probably autosave the new posting during typing, so that in case of some reload/disconnect/battery death the user can continue working on his/her post.

I have not yet researched current possibilities with HTML5 Webstorage and other gimmicks, so without knowing any other widely adoptable solution, I would implement this through one [JSON cookie](https://github.com/js-cookie/js-cookie#json), for which we would have to add js-cookie to `js/vendor`.

**Comment by rizafahmi** [comment]
If you want to do webstorage, I could help

**Comment by rrrene** [comment]
That would be nice! 

You could implement it in `app.js` (we have jQuery included since yesterday :grin:) and it should look for the inputs from `web/templates/posting/form.html.eex`.

I am not yet familar with webstorage, but a cursory google search let me to believe that it might be better  than my cookie-proposal. :+1:

**Comment by rizafahmi** [comment]
@rrrene how to login? Tried to open `/posting/new` but need to authenticate. Tried to skip authentication by commenting it on the controller, but the form need `current_user`.

**Comment by rrrene** [comment]
@rizafahmi my bad! You have to register a GitHub application and connect it with your local Phoenix. 

I added [better usage instructions](https://github.com/rrrene/elixirstatus-web#usage) to the README.
