### ISSUE TITLE
Feature: Compose post before being logged in

### ISSUE THREAD

**Issue by rrrene** [rrrene/elixirstatus-web#11]
Maybe, just maybe, it would be nice if we could display the posting form and let the user type his/her posting, before he/she has to authenticate via GitHub.

I am unsure whether this a great feature we really need (because it lowers the barrier to participate) and how we would store the "draft" of the posting during authentification.

I am open for ideas here!

**Comment by bitwalker** [comment]
Might be worth looking at how StackOverflow does it, since they do basically the same thing. You can type in an answer (maybe a question too, haven't seen that myself), and log in after the fact, and it persists it somehow. I suspect it's in localstorage or something, but haven't really looked.

**Comment by rizafahmi** [comment]
Maybe using a new button, some kind like "Login and post". Is that possible?

**Comment by chrisrp** [comment]
Maybe some sort of dialog? A dialog opens, the user logs in and then have the form posted? Just had this idea but sounds like a lot of front end for me =(
