### ISSUE TITLE
Feature: Pagination for postings

### ISSUE THREAD

**Issue by rrrene** [rrrene/elixirstatus-web#13]
I think we could realize this via [Scrivener](https://github.com/drewolson/scrivener).

`ElixirStatus.PostingController.get_all/0` already builds up a query to load the frontpage postings. This seems like the right place to implement pagination.

Any takers?

**Comment by philnash** [comment]
I'll try to take a look at this. :smiley:

**Comment by philnash** [comment]
I've started work on this in https://github.com/philnash/elixirstatus-web/tree/pagination.

Pagination now works, after upgrading Scrivener, just need to add pagination links to the view.

@rrrene: I was thinking just "previous" and "next" links for the pagination, as presumably this is going to grow quite a way and accessing the last page would grow to be painful for the database. RubyFlow has an infinite scroll, which is essentially the same thing. What do you think?

**Comment by rrrene** [comment]
Great. 

The "mode" of pagination is an interesting point to open up for discussion. 

**Endless scroll**

I personally am not that big a fan of infinte scrolling since you do not have a URL for what you are currently looking at (as in: I can't send you a link to point out a design glitch or something).
Also you lose the option to integrate a footer with boring, but useful stuff like a short description of your site, call for contributions pointing to GitHub, links to social media accounts, contact links, etc.

**Prev/next pagination**

I use this on my blog. Generally I am a fan, but I have to admit it get's tiresome when clicking through the pages when you "just wanted to find that article" (and were to lazy to use search).

**Windowed pagination**

Perfect for things were you go to look up stuff, like alphabetically sorted catalogs.
Also good when you can jump a few pages after you get a sense how far into the past you want to go.
Positive: Super practical for searching ordered sets of data.
Negative: It adds *a lot* of noise to the UI design. And I haven't seen windowed pagination that doesn't look like office software.

--

Now, my sentiment would be we go for a "prev/next" navigation, but we display 20 items per page, so most people won't go to "page 2" since they found all new postings on the frontpage.

What do you think?

**Comment by philnash** [comment]
I think prev/next for now makes most sense. It's fairly simple to do but can be reconsidered if it's not working well. Will try to get that done this weekend.

**Comment by rrrene** [comment]
Looks very good! Thank you!
