### ISSUE TITLE
Feature: RSS controller and feed

### ISSUE THREAD

**Issue by rrrene** [rrrene/elixirstatus-web#2]
We already have postings and a PostingController, but we also need an RSS feed that displays the last X Postings.

We could probably introduce a separate controller for the RSS feed and extract the "load postings for the start page" logic from PostingController to always have the same postings in the feed that are on the frontpage.

**Comment by orendon** [comment]
@rrrene I can put some time on this issue during this week

**Comment by rrrene** [comment]
:+1: That would be great!
