### ISSUE TITLE
Feature: Fixtures

### ISSUE THREAD

**Issue by rrrene** [rrrene/elixirstatus-web#3]
We need some Seeds/Fixtures for testing both via `mix test` and by hand, since nobody wants to repost half a dozen fake announcements everytime he tests features like "delete".

We could probably put the fixtures into an *.exs file in `priv/repo/fixtures`, but from there on I am also lost. Very open for ideas here.

**Comment by rrrene** [comment]
A first step might be to create a `priv/repo/seeds.exs` to gain the ability to seed the database with a dozen intial announcements for manual testing and designing the frontend.

**Comment by Hanspagh** [comment]
And then run it with mix run priv/repo/seeds.exs. In my opinion this makes most sense in regards to manual testing, since using it in unit test would insert a lot of unneeded records?

**Comment by rrrene** [comment]
Exactly.

It would be super nice to some mechanism for unit/integration testing, but as a start we should make something to (re-)seed the dev database, so we can ensure a consistent starting point for manual tests.

**Comment by Hanspagh** [comment]
I will properly have some time to look at it tomorrow, PR incoming :)
