### ISSUE TITLE
Do not parse Markdown when displaying search query

### ISSUE THREAD

**Issue by Techbrunch** [rrrene/elixirstatus-web#35]
Minor improvement, the search query should probably not be parsed as markdown as it will break the layout.

Example: http://elixirstatus.com/?q=%3Ch1%3Etest%3C/h1%3E

The commit: https://github.com/rrrene/elixirstatus-web/commit/63b0b7f50c92ebd3679ee02969332495f4a6ed75

**Comment by rrrene** [comment]
Aaand it's live. Good catch! :+1:
