### ISSUE TITLE
Emojis get eaten (and the following text

### ISSUE THREAD

**Issue by asaaki** [rrrene/elixirstatus-web#36]
#### What did I do?

I wrote an entry with emojis in title and body.
#### What happened?

The emojis as well as the following text were removed after publish/save.
#### What did I expect to happen?

The title and the text should include the emojis and no further harm to my text is done.
#### Example

Ref: http://elixirstatus.com/p/gCHr

Title entered: `TL;DR: 🗜🐳📦 — Strip feature in #EDIB (Elixir Docker Image Builder) makes images even smaller!`
Title after save: `TL;DR:`

(If you have an edit log, it should be visible; I adjusted the title afterwards, so it makes sense again.)
#### Fun Fact

[The tweet is correct.](https://twitter.com/elixirstatus/status/731990011357372416)
#### System

I use `Chrome 50` on `OSX 10.11.4`.

**Comment by rrrene** [comment]
Crap. As a conaisseur of the fine art of emojiism myself, this is not good! :-1: :sob: 

Will fix!

**Comment by asaaki** [comment]
There's a PR open for it.
