### ISSUE TITLE
Feature: Automatically post to @elixirstatus on Twitter

### ISSUE THREAD

**Issue by rrrene** [rrrene/elixirstatus-web#4]
We already have the basic structure in place to post to our Twitter-Account [@elixirstatus](https://twitter.com/elixirstatus).

If you look at the [ElixirStatus.Publisher](https://github.com/rrrene/elixirstatus-web/blob/2b74dffa7d5275f4608a267cb81144acbf3215c1/lib/elixir_status/publisher.ex#L69) module there is a function `update_on_twitter/2` that is already hooked up, but does not do anything.

We have to hook that up via [ExTwitter](https://github.com/parroty/extwitter), making the Twitter account configurable in `prod.secret.exs`.

**Comment by Hanspagh** [comment]
I will gladly implement this, if no one else have shown interest

**Comment by rrrene** [comment]
That would be fantastic! :+1:

**Comment by Hanspagh** [comment]
So, I have add the dependencies and implemented the tweeting functionality, but I am bit lost on how to test this.

**Comment by rrrene** [comment]
You have to register an app with Twitter (similar to GitHub applications): https://apps.twitter.com

You can put google.com as URL and leave the callback field blank. Then you have to configure ExTwitter like [described here](https://github.com/parroty/extwitter#configure).

But be sure not to commit that configuration data! :wink:

**Comment by Hanspagh** [comment]
Ok, I will do that, as some sort of a integration test, but should we do some unit tests aswell? is that even possible?

**Comment by rrrene** [comment]
That's a great question. I am not sure if there are any best practises for this.

It is the reason why I call the `update_on_twitter/2` with `Mix.env` [as 2nd parameter here](https://github.com/rrrene/elixirstatus-web/blob/2b74dffa7d5275f4608a267cb81144acbf3215c1/lib/elixir_status/publisher.ex#L64). So we don't post 10 tweets every test run ;-)

So it would more than suffice if you integrate it and test it locally by hand!

**Comment by Hanspagh** [comment]
So far I have tested by running an instance of iex and calling the function, but that doesn't seem to use the config file, so I have to setup the config by hand each time. Since I am still a little new to elixir, do you know a better way of doing this?

**Comment by rrrene** [comment]
I'd probably just put the credentials in config/config.exs and try not to commit them :grin: 

Just looked at your fork. You can send me a PR with your changes and I will gladly accept it! :+1:

**Comment by Hanspagh** [comment]
I switched to my linux distro, and I can't seem to compile the required oauth deps here. But I can do a PR anyways?

**Comment by rrrene** [comment]
Sure!

**Comment by rrrene** [comment]
Just tested this locally with the real credentials and it works like a charm.

Fantastic!
