### ISSUE TITLE
Doesn't update avatar on github sign in

### ISSUE THREAD

**Issue by schurig** [rrrene/elixirstatus-web#43]
I changed my github image but the app doesn't seem to update it

**Comment by lasseebert** [comment]
I have the same issue. Why was this closed, @schurig?

**Comment by schurig** [comment]
@lasseebert it seemed to be a caching problem

**Comment by lasseebert** [comment]
Ah so it resolved eventually?

**Comment by schurig** [comment]
@lasseebert Yes, I think I had to wait for a few hours and had to sign out and back in again.

**Comment by lasseebert** [comment]
Thanks ;)

**Comment by lasseebert** [comment]
Edit: My avatar is also updated now ;)

**Comment by rrrene** [comment]
@lasseebert @schurig Yeah, the current solution is far from optimal.

A co-worker of mine suggested just hot-linking the GitHub avatars, since ElixirStatus's web traffic should be neglectable.

**Comment by lasseebert** [comment]
Sounds like a reasonable solution :+1:
