### ISSUE TITLE
Slack-friendly (RSS) feed?

### ISSUE THREAD

**Issue by asaaki** [rrrene/elixirstatus-web#45]
Currently when setting up a simple RSS feed integration in a Slack channel, this is how it looks like for each entry:
<img width="697" alt="screenshot 2016-10-24 um 15 47 00" src="https://cloud.githubusercontent.com/assets/446613/19648067/26d31da6-9a01-11e6-8616-78f19f4fcc42.png">

This is most likely due to the HTML used in the RSS template and Slack not being able to display it in a user-friendly way.

**Question would be:**
Can we have a simplified feed (e.g. text only description, or even just the titles only) as an alternative to the current HTML version? WDYT?

**Comment by rrrene** [comment]
Several ElixirStatus users include HTML (formatting, images) in their posts and stripping that would likely lead to an inferior presentation.

I'd accept a PR for a titles-only RSS feed. I think that would be the easiest solution. :+1:

**Comment by davearonson** [comment]
Even in Feedly, the current RSS feed is not very readable.  It is HTML-formatted, apparently as a two-cell table, with usually a large picture on the left, and just whatever tiny space is left on the right for any text.  If this has lists with sublists and such, it gets squished down to the point of being unreadable.  At the very least, the formatting needs to be changed to let the textual part use the full width, such as by changing it from a table to a simple line-break between the picture and text.

**Comment by asaaki** [comment]
Not too relevant for me anymore.
