### ISSUE TITLE
RSS: Internal Server Error

### ISSUE THREAD

**Issue by maxneuvians** [rrrene/elixirstatus-web#54]
RSS appears to be down for the past ~24 hours or so. Visiting the URL http://elixirstatus.com/rss shows an Internal Server Error. Appreciate all the hard work that has gone into the site. 
![screen shot 2017-09-05 at 12 45 12 pm](https://user-images.githubusercontent.com/867334/30072454-57d15050-9238-11e7-9b2f-f66faae7fd7d.png)

**Comment by rrrene** [comment]
Fixed. Sorry for this! :+1:

**Comment by maxneuvians** [comment]
No worries - you guys are awesome!
