### ISSUE TITLE
CSS broken today

### ISSUE THREAD

**Issue by drl123** [rrrene/elixirstatus-web#70]
Tried hitting http://elixirstatus.com/ with both FF (83.0) and Chrome (87.0.4280.67) on macOS and the CSS seems to be broken.  Was working fine yesterday.

![Screen Shot 2020-11-24 at 3 19 36 PM](https://user-images.githubusercontent.com/568926/100146839-7fc49c00-2e68-11eb-8331-d8d2a2820517.png)

**Comment by halostatue** [comment]
More information from the console:

```
[Error] Failed to load resource: the server responded with a status of 404 () (app.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (app.js, line 0)
[Error] ReferenceError: Can't find variable: require
	Global Code (elixirstatus.com:892)
[Error] Failed to load resource: the server responded with a status of 404 () (elixirweekly-thumb.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (logo.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (credo-thumb.png, line 0)
```

**Comment by rrrene** [comment]
@halostatue @drl123 are you still seeing these issues? I was not able to re-produce this on my end (and am at a loss whether or not this might have something to do with Cloudflare).

**Comment by drl123** [comment]
Probably was Cloudflare related.  All seems to be working fine yesterday and today.

**Comment by halostatue** [comment]
Same.

**Comment by rrrene** [comment]
:+1: Nevertheless: Thx very much for reporting! :+1:
